menu:
  主页: /
  归档: /archives
subnav:
  github: 'https://github.com/MurphyL'
  twitter: 'https://twitter.com/MurphyLuo'
  rss: /atom.xml
  mail: 'mailto:murphyl@outlook.com'
rss: /atom.xml
root: /
excerpt_link: null
show_all_link: 展开全文
mathjax: false
open_in_new: false
reward_type: 2
reward_wording: 谢谢你请我吃糖果
alipay: null
weixin: null
toc: 1
toc_hide_index: true
toc_empty_wording: 目录，不存在的…
top: true
baidu_analytics: ''
google_analytics: ''
favicon: /images/coffee_bean.png
avatar: /images/avatar.png
share_jia: true
duoshuo: false
wangyiyun: false
changyan_appid: false
changyan_conf: false
disqus: false
gitment_owner: false
gitment_repo: ''
gitment_oauth:
  client_id: ''
  client_secret: ''
style:
  header: '#4d4d4d'
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'
slider:
  showTags: false
friends:
  此间我们: 'https://cijian.us/'
